### ISSUE TITLE
Register a Pet

### ISSUE THREAD

**Issue by josdem** [josdem/playwright-vetlog#14]
As **a user** I want to create a test for register a pet **so that** I can cover a main functionality

**Given**
- A valid username and password

**When**
- I click on "Register a Pet" link
- I set a valid birthdate, pet type and breed 
- I click on "Submit" button

**Then**
- I should see a "Pet Registered" message
- I should be on [Pet Save](https://vetlog.org/pet/save) page view

**Screenshot**
![register_a_pet](https://github.com/user-attachments/assets/934abf46-9edb-45eb-97d6-08f951c590da)

**Comment by xtron3r** [comment]
Hello, I can see if I can do it?

**Comment by josdem** [comment]
> Hello, I can see if I can do it?

Hello @xtron3r , absolutely , your collaboration is appreciated!, let me know if any questions.

**Comment by josdem** [comment]
Hi @xtron3r please take a look at this PR: https://github.com/josdem/playwright-vetlog/pull/20 I hope this gives you an idea how to create your test, let me know if any questions.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/playwright-vetlog/pull/25
