### ISSUE TITLE
Add ESLint with TypeScript

### ISSUE THREAD

**Issue by josdem** [josdem/playwright-vetlog#28]
As a **user**, I want to add [ESLint](https://khalilstemmler.com/blogs/typescript/eslint-for-typescript/) to this project **so that** I can validate TypeScript good practices

**Acceptance Criteria**
- Add ESLint configuration
- I am able to validate TypeScript good practices

**References**
- https://github.com/josdem/playwright-applitools/blob/master/.eslintrc

**Comment by ahmedhalac** [comment]
@josdem. Can I take this one?

**Comment by josdem** [comment]
> @josdem. Can I take this one?
> 
> 

Absolutely, thank you!

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/playwright-vetlog/pull/38
