### ISSUE TITLE
Update dependencies to the latest version

### ISSUE THREAD

**Issue by josdem** [josdem/playwright-vetlog#29]
As **developer**, I would like to see latest versions in the project **so that** I can be up to date

**Acceptance Criteria**
- NodeJS updated to `v22.11.0`
- Types Node to `22.9.0`

**Comment by ahmedhalac** [comment]
Hi @josdem. Can I work on this?

**Comment by josdem** [comment]
> Hi @josdem. Can I work on this?

Hi @ahmedhalac absolutely, your collaboration is appreciated!, let me know if any questions.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/playwright-vetlog/pull/36
